spring:
  docker:
    compose:
      enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?createDatabaseIfNotExist=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

# 임시 작물 사진 로컬 저장 - 추후 S3로 이전 예정
file:
  upload:
    diary-photo-dir: uploads/diary-photos

